---
- hosts: all
  become: yes

  roles:
    - role: system-basic
    - role: ansible.timezone
      vars:
        ag_timezone: Europe/Berlin
    - role: users
    - role: ansible-role-unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Debian,archive=buster-security'
      - 'o=Debian,a=buster-updates'
      unattended_package_blacklist: [cowsay]
      unattended_mail: 'root'
    - role: system-docker

- name: Web specific setup
  import_playbook: web.yml
