- src: git+https://github.com/jnv/ansible-role-unattended-upgrades.git
  version: v1.9.0
- src: git+https://github.com/adriagalin/ansible.timezone.git
  version: 3.0.0
- src: https://github.com/robertdebock/ansible-role-openssh
  name: sshd
- src: git+https://github.com/24367dfa/ansible-role-dehydrated.git
  version: 1.0.1
