- src: hifis.unattended_upgrades
  version: v1.12.2
- src: git+https://github.com/adriagalin/ansible.timezone.git
  version: 3.0.0
- src: https://github.com/robertdebock/ansible-role-openssh
  name: sshd
- src: git+https://github.com/24367dfa/ansible-role-dehydrated.git
  version: 1.0.3
- src: penguineer.dehydrated_cron
  version: v1.0.0
