---
- hosts: web
  become: yes

  roles:
    - role: apache

  tasks:
    - name: Setup proxy site md.freifunk.net
      include_role:
        name: setup-http-site-proxy
      vars:
        site_name: md.freifunk.net
        proxy_port: 1234
