---
- hosts: web
  become: yes

  vars:
    dehydrated_accept_letsencrypt_terms: True
    dehydrated_contactemail: "{{ server_admin }}"
    dehydrated_domains:
      - name: "md.freifunk.net"
        deploy_challenge_hook: "systemctl reload apache2"
      - name: "grafana.md.freifunk.net"
        deploy_challenge_hook: "systemctl reload apache2"
      - name: "web.md.freifunk.net"
        deploy_challenge_hook: "systemctl reload apache2"

  roles:
    - role: apache
    - role: dehydrated


  tasks:
    - name: Setup proxy site md.freifunk.net
      include_role:
        name: setup-http-site-proxy
      vars:
        site_name: md.freifunk.net
        proxy_port: 1234

    - name: Setup proxy site grafana.md.freifunk.net
      include_role:
        name: setup-http-site-proxy
      vars:
        site_name: grafana.md.freifunk.net
        proxy_port: 3000

    - name: Setup container for bind9-md.freifunk.net
      docker_container:
        name: bind9-md-freifunk-net
        image: "ffmd/bind9-md-freifunk-net:2022060802"
        pull: true
        state: started
        restart_policy: unless-stopped
        detach: yes
        ports:
          # Bind to the external ip address only
          # NOTE: There is also a container for the internal ffmd TLD
        - "{{ ansible_default_ipv4.address }}:53:53/udp"
