---
- hosts: web
  become: yes

  vars:
    dehydrated_accept_letsencrypt_terms: True
    dehydrated_contactemail: "{{ server_admin }}"
    dehydrated_domains:
      - name: "md.freifunk.net"
        deploy_challenge_hook: "systemctl reload apache2"
      - name: "grafana.md.freifunk.net"
        deploy_challenge_hook: "systemctl reload apache2"
      - name: "web.md.freifunk.net"
        deploy_challenge_hook: "systemctl reload apache2"

  roles:
    - role: apache
    - role: dehydrated


  tasks:
    - name: Setup proxy site md.freifunk.net
      include_role:
        name: service-http-proxy
      vars:
        site_name: md.freifunk.net
        proxy_port: 1234

    - name: Setup proxy site grafana.md.freifunk.net
      include_role:
        name: service-http-proxy
      vars:
        site_name: grafana.md.freifunk.net
        proxy_port: 3000

